### ISSUE TITLE
Wrong repository link in Cargo.toml

### ISSUE THREAD

**Issue by laurmaedje** [khonsulabs/interner#1]
I saw this crate on crates.io, clicked on the repository link and was unable to find the source code because it points to the `pot` project. Perhaps this
https://github.com/khonsulabs/interner/blob/30e17298a18a42e709bd1f9f41596a7d5e90d83a/Cargo.toml#L8
should be this 
```toml
repository = "https://github.com/khonsulabs/interner"
```
instead?

**Comment by ecton** [comment]
Thank you for reporting this, you're absolutely right. I sometimes copy and paste the list of fields I need to populate from one project to another, and I clearly missed updating this URL in the process.

I've released v0.2.1 with this updated.
